DROP TABLE IF EXISTS supremes;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS witches;

CREATE TABLE orders (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR (50) NOT NULL,
  creed_declaration TEXT
);

CREATE TABLE supremes (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  royal_lineage BOOLEAN NOT NULL,
  order_id INTEGER,
  CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
);

CREATE TABLE witches (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  element VARCHAR(50) NOT NULL,
  joined_order DATETIME DEFAULT CURRENT_TIMESTAMP
);