INSERT INTO orders (name, creed_declaration)
VALUES 
  ('The Willow Singers', 'Like others before me, I have the gift. But I choose to share it, depending on the light.'),
  ('The Night Embers', 'You have always had the power. You find it within yourself. You find it amongst your kind.'),
  ('The Limp Collectors', 'I am as powerful as the force I am up against. I take what I deserve from those who have wronged me.'),
  ('The Veiled Furies', 'I was born in darkness, I revel in the shadows. My face is not one you can see outside your nightmares.'),
  ('The Oceanid Daughters', 'A witch is the embodiment of demonic feminity. She has as many faces as the Moon.');

INSERT INTO supremes (first_name, last_name, royal_lineage, order_id)
VALUES
  ('Colmena', 'Firbank', 1, 1),
  ('Virginia', 'Woolfrig', 1, 2),
  ('Reena', 'Gaveston', 0, 2),
  ('Charmelia', 'LeRoi', 1, 4),
  ('Katherine', 'Mansfield', 1, 5),
  ('Dora', 'Carrington', 0, 3),
  ('Edwina', 'Bellamy', 0, 4),
  ('Montalva', 'Summers', 1, 3),
  ('Octavia', 'Butler', 1, 5),
  ('Unica', 'Zurn', 1, 2);

INSERT INTO witches (first_name, last_name, element)
VALUES
  ('Jamika', 'Fraser', 'Fire'),
  ('Jackinna', 'London', 'Moonlight'),
  ('Roberta', 'Bruce', 'Fire'),
  ('Petunia', 'Greenaway', 'Forest Scents'),
  ('Derekia', 'Jarman', 'Water'),
  ('Paolin', 'Pasolini', 'Water'),
  ('Heathcath', 'Williams', 'Spirits'),
  ('Sandrice', 'Powell', 'Spirits'),
  ('Emilfi', 'Zola', 'Spirits'),
  ('Sissyria', 'Coalpits', 'Forest Scents'),
  ('Antoinette', 'Capet', 'Water'),
  ('Samuelina', 'Delany', 'Fire'),
  ('Tonyrza', 'Duvert', 'Fire'),
  ('Dennfia', 'Cooper', 'Crystals'),
  ('Monica', 'Bellucci', 'Crystals'),
  ('Samuelina', 'Johnson', 'Blood'),
  ('Johanna', 'Dryden', 'Moonlight'),
  ('Alexanderia', 'Pope', 'Blood'),
  ('Lioneza', 'Johnson', 'Forest Scents'),
  ('Aubrey', 'Beardsley', 'Water'),
  ('Tulsery', 'Luper', 'Blood'),
  ('Willeminha', 'Morris', 'Fire'),
  ('Georgina', 'Shaw', 'Water'),
  ('Arnolean', 'Bennett', 'Fire'),
  ('Algernin', 'Blackwood', 'Forest Scents'),
  ('Rhoda', 'Broughton', 'Spirits'),
  ('Harremis', 'Crane', 'Disease'),
  ('Vitorika', 'DeSica', 'Disease'),
  ('Wilkias', 'Collins', 'Crystals'),
  ('Elizabeth', 'Gaskell', 'Moonlight'),
  ('Gefferina', 'Sand', 'Fire'),
  ('Vernonmia', 'Lee', 'Moonlight'),
  ('Arthury', 'Machen', 'Spirits'),
  ('Frederica', 'Marryat', 'Water'),
  ('Harriet', 'Martineau', 'Forest Scents'),
  ('Geomafi', 'Meredith', 'Decease'),
  ('Margaret', 'Oliphant', 'Spirits'),
  ('Antonella', 'Trollope', 'Water'),
  ('Charlotte', 'Yonge', 'Crystals'),
  ('Horaccia', 'Walpole', 'Fire'),
  ('Mattewiss', 'Lewis', 'Forest Scents'),
  ('Wilareah', 'Bedford', 'Spirits'),
  ('Anne', 'Radcliffe', 'Disease'),
  ('Charlien', 'Brown', 'Crystals'),
  ('Eliza', 'Parsons', 'Fire'),
  ('Susan', 'Hill', 'Spirits'),
  ('Sydney', 'Owenson', 'Moonlight'),
  ('Hubertea', 'Crackanthorpe', 'Water'),
  ('Wilfem', 'Carleton', 'Fire'),
  ('Geraldia', 'Griffin', 'Forest Scents');